Repository jorgicio/jorgicio-gentoo-overlay, pull requests merged in 2021-12, with the labels that each got.

#325 media-video/olive: QPainterPath.patch
  media-video/olive/Manifest
  media-video/olive/files/QPainterPath.patch
  media-video/olive/olive-0.1.2.ebuild
Labels: patch

#326 app-editors/vscodium-bin: Add 1.63.0, remove 1.59.1
  app-editors/vscodium-bin/Manifest
  app-editors/vscodium-bin/vscodium-bin-1.63.0.ebuild
Labels: bump request

#327 net-vpn/haguichi: Bump to 1.4.5
  net-vpn/haguichi/Manifest
  net-vpn/haguichi/haguichi-1.4.5.ebuild
  net-vpn/haguichi/haguichi-9999.ebuild
Labels: bump request

#328 app-editors/atom-bin: Version bump 1.58.0
  app-editors/atom-bin/Manifest
  app-editors/atom-bin/atom-bin-1.58.0.ebuild
Labels: bump request

#329 app-editors/vscodium-bin: Add 1.63.1, remove 1.62.1
  app-editors/vscodium-bin/Manifest
  app-editors/vscodium-bin/vscodium-bin-1.63.1.ebuild
Labels: bump request

#330 app-editors/vscodium-bin: Add 1.63.2, remove 1.62.2
  app-editors/vscodium-bin/Manifest
  app-editors/vscodium-bin/vscodium-bin-1.63.2.ebuild
Labels: bump request

#331 Update PYTHON_COMPAT of dev-python/python-nmap-0.6.1 and net-wireless/kickthemout-9999. Also remove net-wireless/kickthemout-0.1 since it supports python 2.7 only. Not tested. Fixes #313
  dev-python/python-nmap/Manifest
  dev-python/python-nmap/python-nmap-0.6.1.ebuild
  net-wireless/kickthemout/Manifest
  net-wireless/kickthemout/kickthemout-0.1.ebuild
  net-wireless/kickthemout/kickthemout-9999.ebuild
Labels: change dependencies, deprecated package/dependency, patch
